language: ruby
dist: trusty
rvm:
- 2.4.1

install:
  - gem install bundler
  - bundle install

script:
  - ruby extract_contents_csv.rb -t -r
  - tar -czf result.tar.gz results

before_deploy:
  - rm -f .travis.yml .gitignore Gemfile Gemfile.lock extract_contents_csv.rb island_with_administrative_area.csv

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: result.tar.gz
    skip_cleanup: true
    on:
      branch: master

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
    target_branch: with-data
    name: Yana Agun Siswanto
    email: yana.developer@gmail.com
